version: '3.9'

networks:
  iced-latte-network:
    name: iced-latte-network
    external: false

volumes:
  pgdata:

services:
  iced-latte-backend:
    image: 'zufarexplainedit/iced-latte-backend:latest'
    container_name: iced-latte-backend
    environment:
      APP_SERVER_PORT: 8083
      APP_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      DATASOURCE_PORT: 5432
      DATASOURCE_NAME: testdb
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_HOST: iced-latte-postgresdb
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - '8083:8083'
    networks:
      - iced-latte-network
    depends_on:
      - iced-latte-postgresdb
    restart: on-failure

  iced-latte-postgresdb:
    image: 'postgres:13.11-bullseye'
    container_name: iced-latte-postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - iced-latte-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
